CREATE TABLE USER (
    ID  VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CREATED BIGINT NOT NULL,
    ROLE VARCHAR (25) NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO USER (ID,NAME,EMAIL,CREATED,ROLE) VALUES ('101','TestUser','test@test.com', 10233,'admin');