CREATE TABLE USER (
    ID  SERIAL,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO USER (ID,NAME,EMAIL) VALUES ('101','TestUser','test@test.com');